# Change these first
owner: uadeutschland # Your GitHub organization or username, where this repository lives
repo: upptime-uadeutschland # The name of this repository

sites:
  - name: Homepage
    url: https://anonyme-unterverdiener.de/
  - name: 12 Schritte
    url: https://anonyme-unterverdiener.de/12schritte/
  - name: Symptome
    url: https://anonyme-unterverdiener.de/symptome/
  - name: Werkzeuge
    url: https://anonyme-unterverdiener.de/werkzeuge/
  - name: Meetings
    url: https://anonyme-unterverdiener.de/meetings/
  - name: Literatur
    url: https://anonyme-unterverdiener.de/literatur/
  - name: Chairvorlage
    url: https://anonyme-unterverdiener.de/files/UA-Online-Chairvorlage-dt.pdf
  - name: Beispielliteraturlink
    url: https://anonyme-unterverdiener.de/files/UA%20Meetingsmappe%20Deutsch.pdf
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://anonyme-unterverdiener.de/upptime
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
